### PR TITLE
Create data model

### PR DESCRIPTION
**Pull request by chimwemwe007**
## The following were accomplished in this pull request

> Create a new app. Give it a meaningful name.
> Initialize your project with Git.
> Postgres database set up.
> Build project schema.
> Create and run the necessary migration files.
> Table and column names should match the ERD diagram.
> note: photo for users table should be a link to an image
> Foreign keys should be included.
> All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @chimwemwe007,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters setup and the updated Microverse readme
 Kindly add the correct linter setup and please  use the updated version  of the Microverse [readme](https://github.com/microverseinc/readme-template) template for your readme
 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by mckent05 — COMMENTED** [review]
Hi @chimwemwe007, 

# STATUS: INVALID REQUEST ❌ ❌ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have linters setup/running. Please ensure that your linters is correctly setup and are all passing 🙏 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by chimwemwe007** [comment]
Good afternoon, my linter checks on my machine are showing no linter errors, as you can see in the screenshot provided, please confirm on your own machine as well, regards. I dont know what is happening here on github.

Capture

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @chimwemwe007 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
