### PR TITLE
Process data

### PR DESCRIPTION
**Pull request by chimwemwe007**
### The following has been completed in this branch.

- Create model classes with associations for User , Post, Comment and Like
- Use rails console we well as add models to insert and read data.
- Create custom methods for likes, comments and the user posts to call data inside models classes.
ods are working.

### CODE REVIEW

**Comment by chimwemwe007** [comment]
## There are no linter errors but github is showing errors.

linter error

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
Hi @chimwemwe007 🤝 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
👍🏽 All requireents ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Refer to these links in order to fix the linters errors:
  - [ ] https://stackoverflow.com/questions/31272763/invalid-byte-sequence-in-utf-8-ruby
  - [ ] https://github.com/rubocop/rubocop/issues/8230

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chimwemwe007** [comment]
hello, my linters keep saying there are no linter errors but github keeps on showing their is errors still, i have tried to rectify it but still the problem continues. Find attached what it keeps saying when i check my inters on my vs code.

linter fin

**Review by DeliceLydia — COMMENTED** [review]
## Hi @chimwemwe007, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
